const IS_LOADING = 'IS_LOADING';
const IS_ERROR = 'IS_ERROR';
const ADD_POST = 'ADD_POST';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_POST = 'DELETE_POST';
const GET_POST = 'GET_POST';
const GET_ALL_POST = 'GET_ALL_POST';

export { IS_ERROR, IS_LOADING, ADD_POST, UPDATE_POST, DELETE_POST, GET_ALL_POST, GET_POST }