const IS_LOADING = 'IS_LOADING';
const IS_ERROR = 'IS_ERROR';
const ADD_CATEGORY = 'ADD_CATEGORY';
const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
const GET_CATEGORY = 'GET_CATEGORY';
const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';

export { IS_ERROR, IS_LOADING, ADD_CATEGORY, UPDATE_CATEGORY, GET_ALL_CATEGORY, GET_CATEGORY }