
const DELETE_USER = "DELETE_USER";
const SET_USER = "SET_USER";
const IS_ERROR = "IS_ERROR";
const IS_SUCCESS = "IS_SUCCESS";
const IS_LOADING = "IS_LOADING";

export { DELETE_USER, SET_USER, IS_ERROR, IS_SUCCESS, IS_LOADING }